# Generated by Django 5.0.3 on 2024-05-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_alter_desafio_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desafio',
            name='status',
        ),
    ]
